routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');
Route::resource('companies', 'companyController');
Route::resource('employees', 'employeeController');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = [
        'name',
        'email',     
    ];

    public function employees()
    {
    	return $this->hasMany(Employee::class);
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Company;
use Illuminate\Support\Str;
use App\Http\Requests\CompanyStoreRequest;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::paginate(10);
        return view('companies.index', ['companies' => $companies]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyStoreRequest $request)
    {

        $validated = $request->validated();
        $company = new Company($validated);
         if ($request->has('logo')) {
            $imageName = time().'.'.request()->logo->getClientOriginalExtension();
            request()->logo->move(public_path('storage'), $imageName);
            $company->logo = $imageName;
        }
        $company->save();
        return redirect('/companies')->with('success', 'Company saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);
        return view('companies.edit', compact('company')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyStoreRequest $request, $id)
    {
        $validated = $request->validated();

        $company = Company::find($id);
        // Check if a profile image has been uploaded
        if ($request->has('logo')) {
            $imageName = time().'.'.request()->logo->getClientOriginalExtension();
            request()->logo->move(public_path('storage'), $imageName);
            $company->logo = $imageName;
        }
        $company->name =  $validated['name'];
        $company->email = $validated['email'];
        $company->save();

        return redirect('/companies')->with('success', 'Company updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::find($id);
        $company->delete();
        return redirect('/companies')->with('success', 'Company deleted!');
    }
}

resources/views/companies/create.blade.php
@extends('adminlte::page')
@section('title', 'Companies')
@section('content_header')
<h1>Add a Company</h1>
@stop
@section('content')
	<div class="row">
		<div class="col-sm-8">
			<div>
				@if ($errors->any())
				<div class="alert alert-danger">
					<ul>
						@foreach ($errors->all() as $error)
						<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div><br />
				@endif
				<form method="post" action="/companies/" enctype="multipart/form-data">
					@csrf
					<div class="form-group">    
						<label for="name">Name:</label>
						<input type="text" class="form-control" name="name"/>
					</div>
					<div class="form-group">
						<label for="email">Email:</label>
						<input type="text" class="form-control" name="email"/>
					</div>
					<div class="form-group">
						<label for="logo">Logo</label>
						<div class="custom-file">
							<input type="file" class="custom-file-input" name="logo" >
							<label class="custom-file-label" for="exampleInputFile">Choose file</label>
						</div>
						<div class="input-group-append">
							<span class="input-group-text" id="">Upload</span>
						</div>
					</div>
					<button type="submit" class="btn btn-primary">Add</button>
				</form>
			</div>
		</div>
	</div>
@stop

resources/views/companies/edit.blade.php
@extends('adminlte::page')
@section('title', 'Update company')
@section('content_header')
<h1>Update company</h1>
@stop
@section('content')
<div class="row">
	<div class="col-sm-8">
		@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div><br />
		@endif
		<form method="post" action="/companies/{{ $company->id }}" enctype="multipart/form-data">
			@method('PATCH') 
			@csrf
			<div class="form-group">    
				<label for="name">Name:</label>
				<input type="text" class="form-control" name="name" value={{ $company->name }} />
			</div>
			<div class="form-group">
				<label for="email">Email:</label>
				<input type="text" class="form-control" name="email" value={{ $company->email }} />
			</div>
			<div class="form-group">
				<label for="logo">Logo:</label>
				<div class="custom-file">
					<input type="file" class="custom-file-input" name="logo" >
					<label class="custom-file-label" for="exampleInputFile">Choose file</label>
				</div>
				<div class="input-group-append">
					<span class="input-group-text" id="">Upload</span>
				</div>
				<img src="{{ asset('storage/'.$company->logo) }}"> 
			</div>                    
			<button type="submit" class="btn btn-primary">Update</button>
		</form>
	</div>
</div>
@stop

resources/views/companies/index.blade.php
@extends('adminlte::page')
@section('title', 'Companies')
@section('content_header')
<h1>Companies<a href="/companies/create" type="button" class="ml-4 btn btn-primary">Add Company</a></h1>
@stop
@section('content')
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				@if(Session::has('message'))
				<p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
				@endif     
			</div>
			<div class="box-body">
				<table id="laravel_datatable" class="table table-bordered table-striped">
					<thead>
						<tr>
							<th>Id</th>
							<th>Name</th>
							<th>Email</th>
							<th colspan = 2>Actions</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($companies as $company)
						<tr>
							<td>{{ $company->id }}</td>
							<td>{{ $company->name }}</td>
							<td>{{ $company->email }}</td>
							<td>
								<a href="{{ route('companies.edit',$company->id)}}" class="btn btn-primary">Edit</a>
							</td>
							<td>
								<form action="{{ route('companies.destroy', $company->id)}}" method="post">
									@csrf
									@method('DELETE')
									<button class="btn btn-danger" type="submit">Delete</button>
								</form>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
				{{ $companies->links() }}
			</div>
		</div>
	</div>
</div>
@stop