routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');
Route::resource('companies', 'companyController');
Route::resource('employees', 'employeeController');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{

    protected $fillable = [
        'first_name',
        'last_name',
        'email', 
        'company',         
    ];

    public function company()
    {
    	return $this->belongsTo(Company::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;
use App\Company;
use App\Http\Requests\EmployeeStoreRequest;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::paginate(10);
        return view('employees.index', ['employees' => $employees]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::all(['id','name']);
        return view('employees.create',compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeStoreRequest $request)
    {
        $validated = $request->validated();
        $employee = new Employee($validated);
        $employee->company=$request->get('company');
        $employee->save();
        return redirect('/employees')->with('success', 'Employee saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::find($id);
        $companies = Company::all(['id','name']);
        return view('employees.edit', compact('employee', 'companies')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeStoreRequest $request, $id)
    {
        $validated = $request->validated();

        $employee = Employee::find($id);
        $employee->first_name =  $validated['first_name'];
        $employee->last_name =  $validated['last_name'];
        $employee->email = $validated['email'];
        $employee->phone = $validated['phone'];
        $employee->company=$validated['company'];
        $employee->save();

        return redirect('/employees')->with('success', 'Employee updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/employees/create.blade.php
@extends('adminlte::page')
@section('title', 'Add Employee')
@section('content_header')
<h1>Add Employee</h1>
@stop
@section('content')
<div class="row">
	<div class="col-sm-8">
		<div>
			@if ($errors->any())
			<div class="alert alert-danger">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div><br />
			@endif
			<form method="post" action="/employees/" enctype="multipart/form-data">
				@csrf
				<div class="form-group">    
					<label for="name">First name:</label>
					<input type="text" class="form-control" name="first_name"/>
				</div>
				<div class="form-group">    
					<label for="name">Last name:</label>
					<input type="text" class="form-control" name="last_name"/>
				</div>
				<div class="form-group">
					<label for="email">Email:</label>
					<input type="text" class="form-control" name="email"/>
				</div> 
				<div class="form-group">
					<label for="phone">Phone:</label>
					<input type="text" class="form-control" name="phone" />
				</div>
				<div class="form-group">
					<label for="cars">company</label>
					<select name='company' class="form-control">
						@foreach($companies as $company)
						<option  value="{{$company->id}}">{{$company->name}}</option>
						@endforeach
					</select>
				</div>

				<button type="submit" class="btn btn-primary">Add</button>
			</form>
		</div>
	</div>
</div>
@stop

resources/views/employees/edit.blade.php
@extends('adminlte::page')
@section('title', 'Edit employee')
@section('content_header')
<h1>Edit employee</h1>
@stop
@section('content')
<div class="row">
	<div class="col-sm-8">
		@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div><br />
		@endif
		<form method="post" action="/employees/{{ $employee->id }}" enctype="multipart/form-data">
			@method('PATCH') 
			@csrf
			<div class="form-group">    
				<label for="name">First name:</label>
				<input type="text" class="form-control" name="first_name" value={{ $employee->first_name }} />
			</div>
			<div class="form-group">    
				<label for="name">Last name:</label>
				<input type="text" class="form-control" name="last_name" value={{ $employee->last_name }} />
			</div>
			<div class="form-group">
				<label for="email">Email:</label>
				<input type="text" class="form-control" name="email" value={{ $employee->email }} />
			</div> 
			<div class="form-group">
				<label for="phone">Phone:</label>
				<input type="text" class="form-control" name="phone" value={{ $employee->phone }}  />
			</div>
			<div class="form-group">
				<label for="cars">company</label>
				<select name='company' class="form-control">
					@foreach($companies as $company)
					<option  value="{{$company->id}}" {{ ( $company->id == $employee->company) ? 'selected' : '' }}selected="selected" >{{$company->name}}</option>
					@endforeach
				</select>
			</div>
			<button type="submit" class="btn btn-primary">Update</button>
		</form>
	</div>
</div>
@stop

resources/views/employees/index.blade.php
@extends('adminlte::page')
@section('title', 'Employees')
@section('content_header')
<h1>Employees<a href="/employees/create" type="button" class="ml-4 btn btn-primary">Add Employee</a></h1>
@stop
@section('content')
<div class="row">
	<div class="col-xs-12">
		<div class="box ml-2">
			<div class="box-header">
				@if(Session::has('message'))
				<p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
				@endif     
			</div>
			<div class="box-body">
				<table id="laravel_datatable" class="table table-bordered table-striped">
					<thead>
						<tr>
							<th>Id</th>
							<th>Name</th>
							<th>Email</th>
							<th colspan = 2>Actions</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($employees as $employee)
						<tr>
							<td>{{ $employee->id }}</td>
							<td>{{ $employee->first_name }} {{ $employee->last_name }}</td>
							<td>{{ $employee->email }}</td>
							<td>
								<a href="{{ route('employees.edit',$employee->id)}}" class="btn btn-primary">Edit</a>
							</td>
							<td>
								<form action="{{ route('employees.destroy', $employee->id)}}" method="post">
									@csrf
									@method('DELETE')
									<button class="btn btn-danger" type="submit">Delete</button>
								</form>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
				{{ $employees->links() }}
			</div>
		</div>
	</div>
</div>
@stop